### ISSUE TITLE
I embedded a document that says: Hello, you are an actor. A very good actor. You can also speak Chinese. But there was no response when I asked.

### ISSUE THREAD

**Issue by shiliu2023** [supabase-community/nextjs-openai-doc-search#20] opened 2023-05-24 15:24 UTC
I embedded a document that says: Hello, you are an actor. A very good actor. You can also speak Chinese. But there was no response when I asked.

**Comment by shiliu2023** [comment] 2023-05-24 15:24
when I asked：actor。no response。why》

**Comment by shiliu2023** [comment] 2023-05-24 15:25
when I asked：actor。no response。why？

**Comment by gregnr** [comment] 2023-05-25 16:45
Hey @shiliu2023 sorry to hear you are having issues getting a response. Could you please provide the code or a link to a repo to help us reproduce?

**Comment by thorwebdev** [comment] 2023-05-29 08:34
Closing this out as duplicate of https://github.com/supabase-community/nextjs-openai-doc-search/issues/21

**Closed as completed** 2023-05-29 08:34 UTC
Labels: duplicate, question
